### ISSUE TITLE
Discussion: Monoliths over Microservices

### ISSUE THREAD

**Issue by chbrinker** [julz/cloud-native-programming#1]
## Discussion to value 2. "Monoliths over Microservices"

I agree with you in terms that people tend to produce too much microservices. After that they get caught up in managing the introduces complexity. Personally, I like to compare designing a system of microservices with class design from OOP. In that metaphor a microservice equals a class in OOP. If I now use my OOP skillset on the behavior of introducing to much microservices this smells like the unnecessary complexity anti-pattern. What helpes against that pattern is the single responsibility principle. Because it states each class should be responsible for only one thing. But it defines these responsibility not directly by functional aspects. It uses the term of axes of change. Classes are devided if their behavior changes on different axes. So what are axes of change in terms of microservices and cloud native applications? I believe there are three:

1. Behavioral change (frequency and collocation, more on a release level)
2. Scaling change (is the point in time and amount of scaling the same?)
3. People (when separating microservices by 1 team 1 microservice, we introduce solid interfaces and by that contracts by that, which helps with reliability between teams)

So, in my opinion the value should be reformulated to something like:

Monoliths over Microservices - Microservices need an axis of change. Axis of change are...

**Comment by julz** [comment]
Posted a somewhat related discussion [here](https://github.com/julz/cloud-native-programming/issues/3). Tl;dr: this bullet feels like it's getting at a symptom rather than the core problem, but I'm not sure we know exactly how to phrase the problem, yet :-).

I wonder if there's a way to phrase this at a higher level than monoliths/micro-services. Something like "Programming language modularity over infrastructure modularity" maybe? Wdyt?

**Comment by stevepeak** [comment]
My comment at https://github.com/julz/cloud-native-programming/issues/3#issuecomment-519064943 I hope sheds light on this.

I think the title is very misleading: `Monoliths over Microservices`... they are not mutually exclusive. We at [Storyscript](https://storyscript.io) are a monolith powered by microservices, a monolith view of microservices, a language to unite microservices, etc. 

I strongly believe the timing is now for such a language. wdyt?

**Comment by julz** [comment]
Yeah, Im leaning towards this bullet being more like "Programming over infrastructure management" or something higher level that could then mention that we prefer tools and techniques that avoid ending up managing a whole set of Microservices and deployment pipelines and yml. I think actually these conversations are close enough together we might want to merge them so Ill close this in favour of #3.

**Comment by stevepeak** [comment]
**Programming over infrastructure management** is much better.
